#!/bin/bash

if [ "$EUID" != "0" ]; then
  echo "You must be root to run this script. Sorry, dude!"
  exit 1
fi

LXCDIR="/var/lib/lxc"
CONFIG="config_rftest3"

# Setup LXC and base container
#apt-get -y --force-yes install lxc
#mkdir -p $LXCDIR
#lxc-create -t ubuntu -n base_rftest3

#chroot $LXCDIR/base_rftest3/rootfs apt-get update
# !!!
# ADD THE PACKETS YOU NEED TO INSTALL HERE
# !!!
#chroot $LXCDIR/base_rftest3/rootfs apt-get -y --force-yes install quagga libboost-thread-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev rsyslog vlan tcpdump exabgp
# !!!

# Clone the base container to make other containers based on config
cd $CONFIG
for VM in *
do
    lxc-clone -o base_rftest3 -n $VM
    cp -R $VM/* $LXCDIR/$VM
done
